import { useState } from 'react';
import { FlatList, Image, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useTrips } from '../../src/contexts/TripsContext';
import AccountGate from '../../src/components/AccountGate';
import { Action, Field, Message, ui } from '../../src/components/JourneyUI';
export default function Diary() {
  const {trips,loading,error,refresh} = useTrips(); const [query,setQuery] = useState(''); const [favorites,setFavorites] = useState(false);
  const term=query.trim().toLowerCase(); const data=trips.filter(t => (!favorites||t.favorite)&&`${t.title} ${t.location.name} ${t.note}`.toLowerCase().includes(term));
  return <AccountGate><View style={ui.page}><FlatList data={data} keyExtractor={t=>t.id} refreshing={loading} onRefresh={()=>void refresh()} contentContainerStyle={[ui.content,{maxWidth:760}]} ListHeaderComponent={<View style={{gap:16}}><View style={ui.hero}><Text style={{color:'#C9E3AB',letterSpacing:2}}>MY TRAVEL JOURNAL</Text><Text accessibilityRole="header" style={[ui.title,{color:'#FFF'}]}>ไปที่ไหนมา{ '\n' }เล่าให้ความทรงจำฟัง</Text><Text style={{color:'#E4EEE8',fontSize:16}}>เก็บไว้แล้ว {trips.length} การเดินทาง</Text><Action secondary title="＋ บันทึกการเดินทางใหม่" onPress={()=>router.push('/add')} /></View><Field label="ค้นหาทริป สถานที่ หรือความทรงจำ" value={query} onChangeText={setQuery} /><Action secondary selected={favorites} title="แสดงเฉพาะทริปโปรด" onPress={()=>setFavorites(v=>!v)} /><Message text={error} />{error&&<Action title="ลองโหลดอีกครั้ง" onPress={()=>void refresh()} />}</View>} ListEmptyComponent={<View style={ui.card}><Text style={ui.heading}>{loading?'กำลังโหลดบันทึก…':trips.length?'ยังไม่พบเรื่องราวที่ค้นหา':'หน้ากระดาษแรกยังว่างอยู่'}</Text><Text style={ui.text}>{trips.length?'ลองเปลี่ยนคำค้นหรือตัวกรอง':'เริ่มจากทริปใกล้บ้านก็ได้ บันทึกสถานที่ วันที่ และความรู้สึกดี ๆ ของคุณ'}</Text></View>} renderItem={({item})=><View style={ui.card}>{item.photo?<Image accessibilityLabel={`ภาพ ${item.title}`} source={{uri:item.photo}} style={ui.photo} />:<View style={{padding:24,backgroundColor:'#E5EEE8',borderRadius:14}}><Text style={{fontSize:36}}>✦</Text><Text style={ui.text}>{item.location.name}</Text></View>}<Text style={ui.muted}>{item.date} {item.favorite?'· ★ ทริปโปรด':''}</Text><Text accessibilityRole="header" style={ui.heading}>{item.title}</Text><Text style={ui.text}>{item.location.name}</Text>{!!item.note&&<Text numberOfLines={3} style={ui.muted}>{item.note}</Text>}<Action secondary title="เปิดบันทึก" accessibilityLabel={`เปิดบันทึก ${item.title}`} onPress={()=>router.push({pathname:'/trip/[id]',params:{id:item.id}})} /></View>} /></View></AccountGate>;
}
